### ISSUE TITLE
Make 10-H One Top-Level Folder

### ISSUE THREAD

**Issue by AndiH** [FZJ-JSC/tutorial-multi-gpu#19]
Because of the addition of CUDA Graphs, @jirikraus created two folders for the `10` hands-ons; one for NVSHMEM (`10A`), and one for CUDA Graphs (`10B`).

In `08-H` we also have two exercises, one for NCCL and one for NVSHMEM. There, we only have one top-level directory and moved the exercised in individual sub-folders of it.

I'd suggest to make `10-H` like `08-H`. Alternatively, we could also split up `08-H`, but I don't like that too much…

**Comment by jirikraus** [comment]
@AndiH good point. Should be addressed with PR #22
